//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DIRWALK.rc
//
#define IDI_PINGER						101
#define IDC_CANCEL                       6
#define IDC_CLOSE                        7
#define IDC_MYHELP                       8
#define IDD_PING                        102
#define IDC_PING                        1000
#define IDC_ADDRESS                     1001
#define IDC_STATUS                      1002
#define IDC_VERBOSE                     1003
#define IDC_SETTINGS                    1004
#define IDC_NPINGS                      1005
#define IDC_TTLE                        1006
#define IDC_NPINGUD                     1007
#define IDC_NUMPING                     1008
#define IDC_TTL                         1010
#define IDC_TTLUD                       1011
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
